# Generated by Django 2.2.3 on 2019-09-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('follow', '0002_follow_target_group'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='target_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_job', to='jobs.Job'),
        ),
    ]
